"""new wordlist cols

Revision ID: 0af3af608f11
Revises: d93e0262a171
Create Date: 2018-12-02 14:39:13.661180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af3af608f11'
down_revision = 'd93e0262a171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_list', sa.Column('adj_assoc', sa.String(length=120), nullable=True))
    op.add_column('word_list', sa.Column('article', sa.String(length=5), nullable=True))
    op.add_column('word_list', sa.Column('categories', sa.String(length=120), nullable=True))
    op.add_column('word_list', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('word_list', sa.Column('irregular', sa.Integer(), nullable=True))
    op.add_column('word_list', sa.Column('mult_syll', sa.Integer(), nullable=True))
    op.add_column('word_list', sa.Column('noun_assoc', sa.String(length=120), nullable=True))
    op.add_column('word_list', sa.Column('subtype', sa.String(length=16), nullable=True))
    op.add_column('word_list', sa.Column('verb_assoc', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_word_list_adj_assoc'), 'word_list', ['adj_assoc'], unique=False)
    op.create_index(op.f('ix_word_list_categories'), 'word_list', ['categories'], unique=False)
    op.create_index(op.f('ix_word_list_gender'), 'word_list', ['gender'], unique=False)
    op.create_index(op.f('ix_word_list_irregular'), 'word_list', ['irregular'], unique=False)
    op.create_index(op.f('ix_word_list_mult_syll'), 'word_list', ['mult_syll'], unique=False)
    op.create_index(op.f('ix_word_list_noun_assoc'), 'word_list', ['noun_assoc'], unique=False)
    op.create_index(op.f('ix_word_list_subtype'), 'word_list', ['subtype'], unique=False)
    op.create_index(op.f('ix_word_list_tag'), 'word_list', ['tag'], unique=False)
    op.create_index(op.f('ix_word_list_verb_assoc'), 'word_list', ['verb_assoc'], unique=False)
    op.create_index(op.f('ix_word_list_word'), 'word_list', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_list_word'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_verb_assoc'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_tag'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_subtype'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_noun_assoc'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_mult_syll'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_irregular'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_gender'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_categories'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_adj_assoc'), table_name='word_list')
    op.drop_column('word_list', 'verb_assoc')
    op.drop_column('word_list', 'subtype')
    op.drop_column('word_list', 'noun_assoc')
    op.drop_column('word_list', 'mult_syll')
    op.drop_column('word_list', 'irregular')
    op.drop_column('word_list', 'gender')
    op.drop_column('word_list', 'categories')
    op.drop_column('word_list', 'article')
    op.drop_column('word_list', 'adj_assoc')
    # ### end Alembic commands ###
