"""registered User column

Revision ID: 29e50fad55b5
Revises: ac45b52a64fd
Create Date: 2019-02-01 21:47:25.845165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e50fad55b5'
down_revision = 'ac45b52a64fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    # ### end Alembic commands ###
