"""times_played user column

Revision ID: ac45b52a64fd
Revises: 2aa0f7445f22
Create Date: 2019-02-01 00:50:28.659540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac45b52a64fd'
down_revision = '2aa0f7445f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('times_played', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_times_played'), 'user', ['times_played'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_times_played'), table_name='user')
    op.drop_column('user', 'times_played')
    # ### end Alembic commands ###
