"""sentence models and word list

Revision ID: d93e0262a171
Revises: cab20765917f
Create Date: 2018-11-12 19:01:30.951484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93e0262a171'
down_revision = 'cab20765917f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_model_sentence'), 'sentence_model', ['sentence'], unique=True)
    op.create_table('word_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('tag', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_list_tag'), 'word_list', ['tag'], unique=False)
    op.create_index(op.f('ix_word_list_word'), 'word_list', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_list_word'), table_name='word_list')
    op.drop_index(op.f('ix_word_list_tag'), table_name='word_list')
    op.drop_table('word_list')
    op.drop_index(op.f('ix_sentence_model_sentence'), table_name='sentence_model')
    op.drop_table('sentence_model')
    # ### end Alembic commands ###
